#!/bin/bash

# This requires the urfkill package to be installed.
# urkfill will persist the wifi/etc. killswitch over a reboot,
# unlike pure rfkill or the Ubuntu settings.

flags=false
if [ -z "$1" -o "$1" = "on" ]; then
  flags=true
elif [ -n "$1" -a "$1" = "bounce" ]; then
  flags="true false"
else
  flags=false
fi

for flag in $flags; do
  gdbus call -y -d org.freedesktop.URfkill -o /org/freedesktop/URfkill -m org.freedesktop.URfkill.Block 0 $flag
  rfkill list
done

